#!/bin/bash
# Adds AI agent folders to .gitignore

MARKER="# AI Agents - Generated by agent-ignore"
GITIGNORE=".gitignore"

# Resolve symlinks to find actual script location (needed for npx)
SOURCE="${BASH_SOURCE[0]}"
while [ -L "$SOURCE" ]; do
  DIR="$(cd "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
SCRIPT_DIR="$(cd "$(dirname "$SOURCE")" && pwd)"
FOLDERS_FILE="$SCRIPT_DIR/agent-folders.txt"

# Find git root or use current directory
if git rev-parse --git-dir > /dev/null 2>&1; then
  ROOT=$(git rev-parse --show-toplevel)
else
  ROOT=$(pwd)
fi

GITIGNORE_PATH="$ROOT/$GITIGNORE"

# Check if folders file exists
if [ ! -f "$FOLDERS_FILE" ]; then
  echo "Error: $FOLDERS_FILE not found"
  exit 1
fi

# Check if section already exists
if [ -f "$GITIGNORE_PATH" ] && grep -q "$MARKER" "$GITIGNORE_PATH"; then
  echo "AI agents section already exists in .gitignore"
  exit 0
fi

# Append AI agents section
echo "" >> "$GITIGNORE_PATH"
echo "$MARKER" >> "$GITIGNORE_PATH"
cat "$FOLDERS_FILE" >> "$GITIGNORE_PATH"

echo "Added AI agents to $GITIGNORE_PATH"
