const path = require("path");

const MARKER = "# AI Agents - Generated by agent-ignore";
const GITIGNORE = ".gitignore";
const FOLDERS_FILE = path.join(__dirname, "..", "agent-folders.txt");
const AGENTS_TS_URL =
  "https://raw.githubusercontent.com/vercel-labs/skills/refs/heads/main/src/agents.ts";

// Directories to skip when scanning (for performance)
const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  ".next",
  ".nuxt",
  ".output",
  "coverage",
  "vendor",
  "__pycache__",
  ".venv",
  "venv",
]);

module.exports = {
  MARKER,
  GITIGNORE,
  FOLDERS_FILE,
  AGENTS_TS_URL,
  SKIP_DIRS,
};
