import { describe, it, expect } from "vitest";
import { MARKER, GITIGNORE, AGENTS_TS_URL, SKIP_DIRS } from "./constants.js";

describe("constants", () => {
  it("should have correct MARKER value", () => {
    expect(MARKER).toBe("# AI Agents - Generated by agent-ignore");
  });

  it("should have correct GITIGNORE filename", () => {
    expect(GITIGNORE).toBe(".gitignore");
  });

  it("should have valid AGENTS_TS_URL", () => {
    expect(AGENTS_TS_URL).toContain("githubusercontent.com");
    expect(AGENTS_TS_URL).toContain("vercel-labs/skills");
  });

  it("should have SKIP_DIRS as a Set", () => {
    expect(SKIP_DIRS).toBeInstanceOf(Set);
  });

  it("should include common directories in SKIP_DIRS", () => {
    expect(SKIP_DIRS.has("node_modules")).toBe(true);
    expect(SKIP_DIRS.has(".git")).toBe(true);
    expect(SKIP_DIRS.has("dist")).toBe(true);
    expect(SKIP_DIRS.has("build")).toBe(true);
  });
});
