import path from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export const MARKER = "# AI Agents - Generated by agent-ignore";
export const GITIGNORE = ".gitignore";
export const FOLDERS_FILE = path.join(__dirname, "..", "agent-folders.txt");
export const AGENTS_TS_URL =
  "https://raw.githubusercontent.com/vercel-labs/skills/refs/heads/main/src/agents.ts";

// Directories to skip when scanning (for performance)
export const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  ".next",
  ".nuxt",
  ".output",
  "coverage",
  "vendor",
  "__pycache__",
  ".venv",
  "venv",
]);
